field: c6a6830e-daad-4ac0-b66c-2f7628175116
fieldLayouts:
  497314f8-6f6a-486b-9d95-9df75bc02b02:
    tabs:
      -
        elements:
          -
            fieldUid: b5f7ba6a-6604-44ef-9760-b8b75758bd1d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 087caacf-98c3-409b-873c-c4dadecfe3d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6b1ac81-91e3-4e12-9337-c06be978aa6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 793a1988-65c6-420b-93f6-57cc25294b99
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  087caacf-98c3-409b-873c-c4dadecfe3d7:
    contentColumnType: string
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Email
  793a1988-65c6-420b-93f6-57cc25294b99:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:244f7440-a428-4998-8c23-00991784b369'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5f7ba6a-6604-44ef-9760-b8b75758bd1d:
    contentColumnType: text
    fieldGroup: null
    handle: person
    instructions: ''
    name: Name
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b6b1ac81-91e3-4e12-9337-c06be978aa6a:
    contentColumnType: text
    fieldGroup: null
    handle: department
    instructions: ''
    name: Department
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: person
name: Person
sortOrder: 1
