fieldLayouts:
  1122e185-f698-4c5a-8666-40c592a2d3df:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 04ab3c60-f325-48ea-bf96-347befb870e0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b52c17fe-0a41-471c-bc52-05fe035094c9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 64e51b90-5f2d-49a4-8a17-c6a5ff230049
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1e144466-03f6-4d85-8265-a6e61f349ce0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e4b10343-326b-4295-b513-5c0b9a546003
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7d4f5b36-6499-4fcd-813b-eff13059a1c0
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Projects
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0b8b44f0-6b19-4cd5-979e-b2a3d95ca50a
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Series
        sortOrder: 2
handle: series
hasTitleField: true
name: Series
section: 32174234-e8c3-40d4-9725-77ff2bd2366a
sortOrder: 2
titleFormat: ''
