contentColumnType: datetime
fieldGroup: aea8f7d7-487c-42ed-8af7-a33fd4a416e0
handle: date
instructions: ''
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
