contentColumnType: string
fieldGroup: dfe9b0d4-736b-4fbd-a584-88932d8d56a9
handle: typeOfTelevision
instructions: ''
name: 'Type of Television'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: ''
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  source: 'group:17f80f79-7c8b-4415-b3dc-2a1698786289'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
